import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../src/components/Navbar'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>D3E ENERGY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
      </main>

      <footer className={styles.footer}>
        <p> D3E ENERGY - Todos os direitos reservados</p>
      </footer>
    </div>
  )
}

export default Home
