import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '../src/components/Footer'
import Navbar from '../src/components/Navbar'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>D3E ENERGY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.main}>
        <Navbar />
      </nav>
      <main>
        
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  )
}

export default Home
